"""Create agent table

Revision ID: 4e839ad6bcfb
Revises: 
Create Date: 2025-09-18 17:03:22.482736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e839ad6bcfb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=128), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_agent_name'), ['agent_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_agent_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_status'))
        batch_op.drop_index(batch_op.f('ix_agent_agent_name'))

    op.drop_table('agent')
    # ### end Alembic commands ###
